name: uas_ambw_c14210052
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  image_picker: ^1.0.7

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  path_provider: ^2.1.3

  google_fonts: ^6.2.1

  intl: ^0.19.0
  flutter_slidable: ^3.1.0

  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/todolist_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/get_started.png

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/todolist_logo.png"
  android: true
  ios: true
  web: false
